version: 2
jobs:
  build:
    machine:
      image: ubuntu-2004:202101-01
    steps:
      - checkout
      - run:
          name: build-libgit2
          command:
            export GITIN_FORCE_INSTALL=YES && make build-libgit2
      - run:
          name: install
          command:
            go install --tags "static" ./cmd/gitin
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
