name: golangci-lint
on: [push]
permissions:
  contents: read
jobs:
  golangci:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.50.1

          # Optional: if set to true then the action will use pre-installed Go.
          skip-go-installation: true
